name: LowCore
version: '1.4.0'
main: dev.jalikdev.lowCore.LowCore
api-version: '1.21'
author: 'jan'

# -------------------------------------------------
# COMMANDS
# -------------------------------------------------
commands:

  lowcore:
    description: Main command for LowCore
    usage: /lowcore
    permission: lowcore.command
    aliases: [lc]

  fly:
    description: Toggles flight
    usage: /fly
    permission: lowcore.fly

  gm:
    description: Changes gamemode
    usage: /gm
    permission: lowcore.gm
    aliases: [gamemode]

  ec:
    description: Open your ender chest or another player's
    usage: /ec [player]
    permission: lowcore.ec
    aliases: [enderchest]

  invsee:
    description: View another player's inventory
    usage: /invsee <player>
    permission: lowcore.invsee

  hat:
    description: Put the item in your hand on your head
    usage: /hat [player]
    permission: lowcore.hat
    aliases: [head]

  heal:
    description: Heal yourself or others
    usage: /heal [player]
    permission: lowcore.heal

  feed:
    description: Feed yourself or others
    usage: /feed [player]
    permission: lowcore.feed

  spawnmob:
    description: Spawn a Mob
    usage: /spawnmob <mob> [amount]
    permission: lowcore.spawnmob
    aliases: [spawnentity, summonmob]

  enchant:
    description: Enchant and modify items
    usage: /enchant <...>
    permission: lowcore.enchant

  anvil:
    description: Opens an anvil interface
    usage: /anvil
    permission: lowcore.anvil

  repair:
    description: Repairs your held item or all items
    usage: /repair [all]
    permission: lowcore.repair

  craft:
    description: Opens a crafting table
    usage: /craft
    permission: lowcore.craft
    aliases: [workbench]

  vanish:
    description: Toggle vanish mode
    usage: /vanish
    permission: lowcore.vanish
    aliases: [v]

  speed:
    description: Change your walk or fly speed
    usage: /speed <1-10>
    permission: lowcore.speed

  god:
    description: Toggle god mode
    usage: /god
    permission: lowcore.god
    aliases: [invincibility]

  killall:
    description: Kill mobs globally or in a radius
    usage: /killall [type] [radius]
    permission: lowcore.killall
    aliases: [killmob]

  log:
    description: View recent admin actions
    usage: /log [amount]
    permission: lowcore.log

  cleanup:
    description: Open the lag cleanup GUI
    usage: /cleanup
    permission: lowcore.cleanup
    aliases: [ lag, clearlag ]

  performance:
    description: Show server performance
    usage: /performance
    permission: lowcore.performance
    aliases: [perf, tps]

  sudo:
    description: Execute a command or send a message as another player
    usage: /sudo <player> <command or message>
    permission: lowcore.sudo
    permission-message: §cYou do not have permission to use this command.

  lastlogout:
    description: Shows the last logout location of a player
    usage: "/lastlogout <player>"
    permission: lowcore.lastlogout



# -------------------------------------------------
# PERMISSIONS
# -------------------------------------------------
permissions:

  lowcore.command:
    description: Use /lowcore
    default: op

  lowcore.fly:
    description: Use /fly
    default: op

  lowcore.gm:
    description: Use /gm
    default: op

  lowcore.ec:
    description: Open your ender chest
    default: op
  lowcore.ec.others:
    description: Open others' ender chests
    default: op

  lowcore.invsee:
    description: View inventories
    default: op

  lowcore.hat:
    description: Use /hat on yourself
    default: true
  lowcore.hat.others:
    description: Use /hat on others
    default: op

  lowcore.heal:
    description: Heal yourself
    default: op
  lowcore.heal.others:
    description: Heal others
    default: op

  lowcore.feed:
    description: Feed yourself
    default: op
  lowcore.feed.others:
    description: Feed others
    default: op

  lowcore.spawnmob:
    description: Spawn mobs
    default: op

  lowcore.enchant:
    description: Enchant items
    default: op

  lowcore.performance:
    description: Use /performance
    default: op

  lowcore.cleanup:
    description: Use the lag cleanup GUI
    default: op

  lowcore.sudo:
    description: Make someone say something
    default: op
  lowcore.sudo.op:
    description: All sudo permissions!
    default: op


  permissions:
    lowcore.lastlogout:
      description: Allows the use of /lastlogout
      default: op