name: LowCore
version: '1.2.0'
main: org.jalikdev.lowCore.LowCore
api-version: '1.21'
author: 'jan'

commands:
  lowcore:
    description: Main command for LowCore
    usage: /lowcore
    permission: lowcore.command

  fly:
    description: Toggles flight
    usage: /fly
    permission: lowcore.fly

  gm:
    description: Changes gamemode
    usage: /gm
    permission: lowcore.gm

  ec:
    description: Open your ender chest or another player's
    usage: /ec [player]
    permission: lowcore.ec

  invsee:
    description: View another player's inventory
    usage: /invsee <player>
    permission: lowcore.invsee

  hat:
    description: Put the item in your hand on your head
    usage: /hat [player]
    permission: lowcore.hat

  heal:
    description: Heal yourself or others
    usage: /heal [player]
    permission: lowcore.heal

  feed:
    description: Feed yourself or others
    usage: /feed [player]
    permission: lowcore.feed

  spawnmob:
    description: Spawn a Mob
    usage: /spawnmob <mob> [amount]
    permission: lowcore.spawnmob

  enchant:
    description: Enchant and modify items.
    usage: /enchant <enchant> [level] | /enchant remove <enchant> | /enchant clear | /enchant name <name> | /enchant resetname
    permission: lowcore.enchant

  anvil:
    description: Opens an anvil interface.
    usage: /anvil
    permission: lowcore.anvil

  repair:
    description: Repairs your held item or all items.
    usage: /repair [all]
    permission: lowcore.repair

  craft:
    description: Opens a crafting table.
    usage: /craft
    permission: lowcore.craft

  workbench:
    description: Alias for /craft
    usage: /workbench
    permission: lowcore.craft

  vanish:
    description: Toggle vanish mode (hidden from players & tab, fake leave/join).
    usage: /vanish
    permission: lowcore.vanish

  speed:
    description: Change your walk or fly speed (1-10).
    usage: /speed <1-10>
    permission: lowcore.speed

permissions:
  lowcore.command:
    description: Use /lowcore
    default: op

  lowcore.fly:
    description: Use /fly
    default: op

  lowcore.gm:
    description: Use /gm
    default: op

  lowcore.ec:
    description: Open own ender chest
    default: op
  lowcore.ec.others:
    description: Open others' ender chests
    default: op

  lowcore.invsee:
    description: View other players' inventories
    default: op

  lowcore.hat:
    description: Use /hat on yourself
    default: true
  lowcore.hat.others:
    description: Use /hat on other players
    default: op

  lowcore.heal:
    description: Heal yourself
    default: op
  lowcore.heal.others:
    description: Heal others
    default: op

  lowcore.feed:
    description: Feed yourself
    default: op
  lowcore.feed.others:
    description: Feed others
    default: op

  lowcore.spawnmob:
    description: Spawn a Mob
    default: op

  lowcore.enchant:
    description: Enchant items etc.
    default: op
