name: LowCore
version: '1.1.3'
main: org.jalikdev.lowCore.LowCore
api-version: '1.21'
author: 'jan'

commands:
  lowcore:
    description: Main command for LowCore
    usage: /lowcore
  fly:
    description: Toggles flight
    usage: /fly
  gm:
    description: Changes gamemode
    usage: /gm
  ec:
    description: Open your ender chest or another player's
    usage: /ec [player]
  invsee:
    description: View another player's inventory
    usage: /invsee <player>
  hat:
    description: Put the item in your hand on your head
    usage: /hat [player]
  heal:
    description: Heal yourself or others
    usage: /heal [player]
  feed:
    description: Feed yourself or others
    usage: /feed [player]
  spawnmob:
    description: Spawn a Mob
    usage: /spawnmob <mob> [amount]

permissions:
  lowcore.hat:
    description: Use /hat on yourself
    default: true
  lowcore.hat.others:
    description: Use /hat on other players
    default: op

  lowcore.invsee:
    description: View other players' inventories
    default: op

  lowcore.ec:
    description: Open own ender chest
    default: op
  lowcore.ec.others:
    description: Open others' ender chests
    default: op

  lowcore.heal:
    description: Heal yourself
    default: op
  lowcore.heal.others:
    description: Heal others
    default: op

  lowcore.feed:
    description: Feed yourself
    default: op
  lowcore.feed.others:
    description: Feed others
    default: op

  lowcore.spawnmob:
    description: Spawn a Mob
    default: op